/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.Monster;
import javax.swing.ImageIcon;

/**
 *
 * @author Juanjo
 */
public class MonsterView extends javax.swing.JPanel {

	private Monster monsterModel;
	
	public void setMonster(Monster monster){
		monsterModel = monster;
		
		monsterNameLabel.setText(monsterModel.getName());
		monsterLevelLabel.setText(Integer.toString(monsterModel.getCombatLevel()));
		prizeView.setPrize(monsterModel.getTreasuresGained(), monsterModel.getLevelsGained());
		badConsequenceView.setBadConsequence(monsterModel.getBadConsequence());
		
		monsterImage.setIcon(new ImageIcon(this.getClass().getResource("/Resources/Monsters/" + monsterModel.getName() + ".jpg")));
	}
	/**
	 * Creates new form MonsterView
	 */
	public MonsterView() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        monsterImage = new javax.swing.JLabel();
        monsterNameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        monsterLevelLabel = new javax.swing.JLabel();
        prizeView = new GUI.PrizeView();
        badConsequenceView = new GUI.BadConsequenceView();

        monsterImage.setText("jLabel1");

        monsterNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        monsterNameLabel.setText("Nombre");

        jLabel3.setText("Nivel:");

        monsterLevelLabel.setText("Niv");

        prizeView.setBorder(javax.swing.BorderFactory.createTitledBorder("Buen rollo"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(monsterImage, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(monsterNameLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(monsterLevelLabel))
                            .addComponent(prizeView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(badConsequenceView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(monsterNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(monsterLevelLabel))
                        .addGap(18, 18, 18)
                        .addComponent(prizeView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(monsterImage, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(badConsequenceView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.BadConsequenceView badConsequenceView;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel monsterImage;
    private javax.swing.JLabel monsterLevelLabel;
    private javax.swing.JLabel monsterNameLabel;
    private GUI.PrizeView prizeView;
    // End of variables declaration//GEN-END:variables
}
